### ISSUE TITLE
两个变量重命名

### ISSUE THREAD

**Issue by ZeroDesigner** [orca233/DeepSS2GO_Predict#1]
Predict.py 文件中，17行，18行中，
```
@ck.option('--terms-file', '-tf', default='data/terms_all.pkl', help='List of predicted terms')
@ck.option('--annotations-file', '-tf', default='data/train_data.pkl', help='Experimental annotations')
```
terms_all.pkl 和 train_data.pkl 都被命名为tf

**Comment by orca233** [comment]
> Predict.py 文件中，17行，18行中，
> 
> ```
> @ck.option('--terms-file', '-tf', default='data/terms_all.pkl', help='List of predicted terms')
> @ck.option('--annotations-file', '-tf', default='data/train_data.pkl', help='Experimental annotations')
> ```
> 
> terms_all.pkl 和 train_data.pkl 都被命名为tf


Have modified. Thx for suggestion!
